dinofrontend/dino_ui_library

package.json
src/components/FormContainer/index.tsx
src/components/FormContainer/types.ts
src/context/index.tsx
src/index.tsx

1) Add React Hook Form  shouldFocusError , shouldUnregister properties for Form Container
2) Export RadioGroup from ui-library

Add React Hook Form  shouldFocusError , shouldUnregister properties 

---

src/components/Radio/RadioGroup.tsx

remove locale state

---

package.json
src/components/Checkbox/index.tsx
src/components/Checkbox/types.ts

Add Link for Checkbox component

Add Link for Checkbox component

---

src/index.tsx

export  form context

---

package.json
src/components/FormField/index.tsx

add react hook form error message

add react hook form error message

---

package.json
src/components/Snackbar/index.tsx
src/components/Snackbar/types.ts
src/index.tsx
src/stories/Snackbar.stories.tsx

- export `useGetSnackbar` customHook

change snackbar logic

---

package.json
src/components/Tooltip/index.tsx
src/components/Tooltip/types.ts
src/stories/Tooltip.stories.tsx

- calculate tooltip positions depends on id

add id for tooltip props

---

package.json
src/components/FileUpload/index.tsx
src/components/FileUpload/types.ts
src/components/FileUpload/uploadItems/index.tsx
src/components/FileUpload/uploadItems/types.ts
src/components/FormField/index.tsx
src/utils/index.tsx

handle files click

---

package.json
src/components/Select/SharedComponents/ContentTop.tsx
src/components/Select/SingleSelect.tsx
src/components/Select/types.ts

add single select option search

add single select option search

---

package.json
src/components/Menu/index.tsx
src/components/Select/MultiSelect/Grouped/index.tsx
src/components/Select/MultiSelect/Multi/index.tsx
src/components/Select/MultiSelect/WithTabs/index.tsx
src/components/Select/MultiSelect/consts.ts
src/components/Select/SharedComponents/ContentTop.tsx
src/components/Select/SingleSelect.tsx
src/components/Select/types.ts
src/hooks/index.tsx
src/stories/Select.stories.tsx
src/stories/SideSheet.stories.tsx

- fix menu component item click

fix multi select content top items visibility

---

package.json
src/components/Input/index.tsx
src/components/Input/types.ts
src/stories/Form.stories.tsx

add react numeric format

---

package.json
src/components/Link/index.tsx
src/components/Link/types.ts
src/stories/Link.stories.tsx

add before after link texts

---

package.json
src/components/Select/MultiSelect/index.tsx
src/hooks/useHideBodyScroll.ts

- fix multiselect items update logic

fix `useHideBodyScroll` functional

---

package.json
src/components/Button/index.tsx
src/components/Button/types.ts
src/stories/Button.stories.tsx

add autofocus property for button

Add autofocus property for button

---

package.json
src/components/Button/index.tsx
src/components/DatePicker/RangeDatePicker.tsx
src/components/DatePicker/SimpleDatePicker.tsx
src/components/DatePicker/TimePicker.tsx
src/components/DatePicker/types.ts
src/stories/DatePicker.stories.tsx

add localization for date pickers

---

package.json
src/components/Select/MultiSelect/Grouped/index.tsx

fix grouped multiselect filter

---

package.json
src/components/DatePicker/index.scss

- hide previous and next month days in date picker

fix date picker month days

---

package.json
src/components/CardSelect/CardSelect.tsx
src/components/CardSelect/types.ts
src/components/Checkbox/Checkbox.tsx
src/components/Counter/Counter.tsx
src/stories/CardSelect.stories.tsx
src/stories/Checkbox.stories.tsx
src/stories/Counter.stories.tsx
src/stories/FileUpload.stories.tsx
src/stories/Select.stories.tsx

change card select types

---

package.json
src/components/Input/Input.tsx
src/components/Input/types.ts

add **isAllowed (values) => boolean** | A checker function to validate the input value. If this function returns false, the onChange method will not get triggered and the input value will not change.

isAllowed property for numeric input

---

src/components/Collapse/CollapseGroup/CollapseGroup.tsx
src/components/Collapse/types.ts

fix: added classname prop for collapse group

fix: added classname prop for collapse group

---

src/components/ItemSelect/ItemSelect.tsx
src/components/Radio/Radio.tsx
src/components/Radio/types.ts

Fix item select component 

---

src/components/OneTimePassword/OneTimePassword.tsx
src/components/OneTimePassword/types.ts
src/stories/OneTimePassword.stories.tsx

fix: autofocus issue
